blank_issues_enabled: false
contact_links:
  - name: Clash.Meta Community Support
    url: https://github.com/MetaCubeX/Clash.Meta/discussions
    about: Please ask and answer questions about Clash.Meta here.
